language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install -r requirements.dev.txt
  - pip install coveralls
# command to run tests
script:
  - pep8
  - flake8
  - nosetests --with-coverage --cover-branches --cover-erase
after_success:
  coveralls
